### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by diilmac** [ShaiShulman/CompaniesHouse_exporter#1]
python companies_house_exporter.py -n -d -f "xls_file_template.xlsx"
Traceback (most recent call last):
  File "C:\tools\Cmder\CompaniesHouse_exporter\companies_house_exporter.py", line 18, in <module>
    from ch_api import get_profile, get_officers
  File "C:\tools\Cmder\CompaniesHouse_exporter\ch_api.py", line 6, in <module>
    from requests.auth import HTTPBasicAuth
ModuleNotFoundError: No module named 'requests'

**Comment by diilmac** [comment]
fixed
